#!/bin/bash
set -e

echo Running ruff src
uvx ruff check --fix src
echo Running ruff tests
uvx ruff check --fix tests
echo Running black src tests
uvx black src tests
echo Running isort src tests
uvx isort --profile black src tests
echo Running flake8 src tests
uvx flake8 src tests
echo Running mypy src
uvx mypy src tests
echo Linting complete!
exit 0
